### ISSUE TITLE
Unable to use/show Paypal with 1.4.0 Thitybees new installation

### ISSUE THREAD

**Issue by sisland** [thirtybees/thirtybees#1704]
I install on my webserver (not visible unless you change your host's file) a new Thirtybees installation. All went fine until I tried to use Paypal before going live to see if works. 

I installed the module from [here](https://github.com/thirtybees/paypal/releases) and configured the module according to the docs. On Checkout, I can't see Paypal. **Carrier Restrictions were checked, and Paypal is enabled for ALL**

Some useful screenshots:
Modules, Payments --> (Missing checkboxes / Radio?)
![mISSING](https://github.com/thirtybees/thirtybees/assets/26673196/25d1d20c-22a8-4b6a-a8cc-117fa5cbb78a)

Modules seem OK according to this:
![2023_07_22_00_56_13_Modules](https://github.com/thirtybees/thirtybees/assets/26673196/0ce0cbfb-294a-48af-b0a5-e9cb1448717a)

Any idea why isn't working?
Thanks!

**Comment by getdatakick** [comment]
There was a caching issue in AdminPaymentController. This issue prevented displaying checkboxes/radioboxes.

Fixed in bleeding edge.

**Comment by getdatakick** [comment]
Thanks for reporting this issue!

**Comment by sisland** [comment]
@getdatakick Thanks but, after using the migration tool, and the ThirtyBees updater I still have the 1.0.8 on my Thirtybees backend. What should I do in order to have the latest version? is the Bleeding Edge the latest 1.4.0?

**Comment by getdatakick** [comment]
install `coreupdater` module

**Comment by sisland** [comment]
Thanks @getdatakick , but now my store has an error like This category is currently unavailable. Can I know what the changes related to the radio boxes in modules , Payment and then edit the affected files manually?

**Comment by getdatakick** [comment]
See the commit associated with this issue: https://github.com/thirtybees/thirtybees/commit/136017aedcbf46f708b31df96ea2c11fd8acecf3

Not something that should have impact on displaying categories in front office. Do you have these categories active/enabled?

**Comment by sisland** [comment]
Thanks will try, but even with the Bleeding Edge version, and with the Paypal Checked (under modules, Payments) I can't use Paypal at Checkout. I mean, it doesn't show anywhere

**Comment by sisland** [comment]
@getdatakick  please, leave this open. As explained the issue persists with the Bleeding Edge version. I double-checked and the Paypal checkbox is indeed "checked", shows as correctly configured but I can't see it at checkout as a payment option. No carrier or country restriction. What else can I do?

Thanks

**Comment by getdatakick** [comment]
I can't reproduce this.

I installed the module on latest bleeding edge, set credentials and enabled WEBSITE PAYMENTS STANDARD

![image](https://github.com/thirtybees/thirtybees/assets/34651851/aa91defb-fc6a-42d8-b485-7d65d6fcd1dc)

In Modules and services > Payment I've set Rurency restriction radiobox to Customer Currency, and enabled all other chckboxes for Group / Country / Carrier

![image](https://github.com/thirtybees/thirtybees/assets/34651851/95564a93-b7df-4fce-8fb6-37438045e38e)

With this settings, paypal option is displayed on front office during checkout:

![image](https://github.com/thirtybees/thirtybees/assets/34651851/cef2ead1-92fd-4f4f-8c5e-a72af91530c1)

I don't see any problem in thirtybees / module.

**Comment by sisland** [comment]
Hi @getdatakick, thanks for taking the time to review this.

1. I have the exact same settings, the only difference is my website isn't live (is on a VPS server but you can only see the website if you change the hosts file)

I also have the same config under Modules, Payments, and the green message about:

All profiles have been loaded correctly:
Website Payments Standard:  

What can I make to debug and found what's happening?

**Comment by getdatakick** [comment]
can you send me access credentials to your back office to "petr@thirtybees.com", I can have a look
