### ISSUE TITLE
Country "Contains states" settings is ignored when resolving zone

### ISSUE THREAD

**Issue by getdatakick** [thirtybees/thirtybees#613]
forum post: https://forum.thirtybees.com/topic/2055/error-messages-when-adding-orders-from-the-backend

Adding orders from the backend works for some customers but for others not. I can’t figure out why it works only for some.

Error messages: No carrier can be applied to this order

**Comment by getdatakick** [comment]
It's possible this issue was solved together with #612, but I can't verify. Awaiting confirmation from @30knees

**Comment by 30knees** [comment]
@getdatakick Unfortunately not. After adding a product the error message still appears.

**Comment by getdatakick** [comment]
Thirtybees ignores *Contains states* settings on Country records when resolving zone id for given address.

How to reproduce this issue:

1) create new Address in Italy
2) create new zone E2
3) disable zone Europe
4) associate Italy with zone E2
5) set *Contains states* = false for Italy
5) remove all carriers from zone Europe
6) enable some carrier for zone E2
5) try to create order for the address created in step 1

It's not possible to create an order.

To fix this, one would have to go over all States within Italy, and associate them with zone E2. Even though settings claims there are no States within Italy.
